agents:
  queue: platform

steps:
- name: ":go: Check go fmt"
  key: go-fmt
  command: .buildkite/steps/test-go-fmt.sh
  plugins:
  - docker#v5.8.0:
      image: golang:1.19
      workdir: /go/src/github.com/buildkite/buildkite-agent-scaler

- name: ":golang: Run Tests"
  key: test
  command: .buildkite/steps/tests.sh
  plugins:
  - docker#v5.8.0:
      image: golang:1.19
      workdir: /go/src/github.com/buildkite/buildkite-agent-scaler

- name: ":docker: Linting"
  key: docker-lint
  commands:
    - "echo \"--- :docker: Hadolint\""
    - "docker run --rm -i hadolint/hadolint < Dockerfile"

- name: ":docker: Build"
  key: docker-build
  depends_on: docker-lint
  branches: "!zego"
  commands:
    - "echo \"--- :docker: Building Docker image\""
    - "docker build -t buildkite-agent-scaler ."

- label: ":docker: Building and pushing image to ECR"
  branches: "zego"
  depends_on: docker-lint
  plugins:
    - seek-oss/docker-ecr-publish#v2.5.0:
        ecr-name: buildkite-agent-scaler
        account_id: "197161164104"
        region: eu-west-1
        tags: ${BUILDKITE_COMMIT}
